app:
  vendors-file: vendors.csv
  models-file: models.csv
  images-large: images-large
  images-small: images-small
  ski-file: ski.csv
  boots-file: boots.csv

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/icepeak
    username: postgres
    password: postgres


  batch:
    jdbc:
      initialize-schema: ALWAYS