app:
  vendors-file: vendors.csv
  ski-models-file: ski-models.csv

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/icepeak_test
    username: postgres
    password: postgres


  batch:
    jdbc:
      initialize-schema: ALWAYS