app:
  vendors-file: vendors.csv
  ski-models-file: ski-models.csv
  ski-images-large: ski-images-large
  ski-images-small: ski-images-small
  ski-file: ski.csv

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/icepeak
    username: postgres
    password: postgres


  batch:
    jdbc:
      initialize-schema: ALWAYS