app:
  vendors-file: data/vendors.csv
  models-file: data/models.csv
  images-large: data/images-large
  images-small: data/images-small
  ski-file: data/ski.csv
  boots-file: data/boots.csv
  users-file: data/users.csv

spring:
  datasource:
    url: jdbc:postgresql://localhost:8081/icepeak
    username: postgres
    password: postgres


  batch:
    jdbc:
      initialize-schema: ALWAYS