logging:
  level:
    root: INFO
    org:
      springframework:
        security: ERROR
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/icepeak
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true


  jackson:
    time-zone: Europe/Moscow

app:
  cancel-old-orders-interval: 3
  cancel-task-rate: 180000

    