version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/icepeak
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - LOGGING_LEVEL_ROOT=INFO
    container_name: api
    networks:
      - nw
  postgres:
    image: "postgres"
    container_name: "postgres"
    ports:
      - "8081:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=icepeak
    networks:
      - nw
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    networks:
      - nw
networks:
  nw: